### ISSUE TITLE
Get results in a decimal form

### ISSUE THREAD

**Issue by DouglasdeMoura** [jiggzson/nerdamer#8] opened 2015-07-22 16:30 UTC
Is it possible to make the LaTeX generator return the decimal value instead of the fraction?

`3/10 = 0.3 instead of 3/10`

I know that we will face a floating point issue (because the result will be 0.30000000000000004). Perhaps add a BigDecimal library to handle it?

**Comment by jiggzson** [comment] 2015-07-22 21:58
Currently no. In the demo it's currently done by looking at the return and then converting it to a decimal. It's one of those things that got pushed to that magical place called tomorrow in the past.

**Comment by jiggzson** [comment] 2016-03-30 16:24
The issue is addressed and fixed in version 0.6.0.

**Closed by jiggzson** 2016-03-30 16:24 UTC
