### ISSUE TITLE
expansion of fraction inside sqrt

### ISSUE THREAD

**Issue by yosuke** [jiggzson/nerdamer#401] opened 2018-03-06 02:00 UTC
What I expect:
```
> nerdamer('sqrt(a/b)').evaluate({a:-1,b:-1}).toString()
"1"
```
What I get:
```
> nerdamer('sqrt(a/b)').evaluate({a:-1,b:-1}).toString()
"-1"
```

This is probably because the fraction inside the sqrt is expanded as follows:
```
> nerdamer('sqrt(a/b)').evaluate().toString()
"sqrt(a)*sqrt(b^(-1))"
```

I think the resulting formula should be "sqrt(a)*(sqrt(b)^(-1))". But even if I assume I got the correct formula, I still cannot get the expected result:
```
> nerdamer('sqrt(a)*(sqrt(b)^(-1))').evaluate({a:-1,b:-1}).toString()
"(-i+6123233995736766/100000000000000000000000000000000)*i"
```

Tested on http://nerdamer.com/demo_dev.html

**Comment by Happypig375** [comment] 2018-03-06 05:09
According to Wolfram Alpha,
sqrt(a/b) == sqrt(a)\*sqrt(b^(-1)) == sqrt(a)\*(sqrt(b)^(-1))
when a and b are positive.
This transformation is not valid for negative and complex numbers though, which you are doing.
This should be addressed in #350, although this one specific transformation can be temporarily disabled until that is implemented.

The fact that (-i+6123233995736766/100000000000000000000000000000000)\*i is returned are bugs though,
because nerdamer('sqrt(-1)\*(sqrt(-1)^(-1))').toString() => "1" but nerdamer('sqrt(a)\*(sqrt(b)^(-1))').evaluate({a:-1,b:-1}).toString() =>  "(-i+6123233995736766/100000000000000000000000000000000)\*i".

**Comment by yosuke** [comment] 2018-03-06 06:09
Just find out the explanation on why "sqrt(a)(sqrt(b)^(-1))" can only stand when both a and b are positive:

https://math.stackexchange.com/questions/1274167/imaginary-fraction-square-root

Realized confirming both fraction element when transforming the formula is the right way.

**Comment by jiggzson** [comment] 2018-03-06 13:34
@yosuke, since the transformation to sqrt(a)\*(sqrt(b)^(-1)) requires no additional conditions, I would think that this would be the better route. Make the switch is not difficult at all. The one that I find interesting is nerdamer('sqrt(a)\*(sqrt(b)^(-1))').evaluate({a:-1,b:-1}).toString(). I'm really curious what led to that. I'm hoping to get to this one soon.

**Comment by Happypig375** [comment] 2018-03-06 13:40
http://www.wolframalpha.com/input/?i=sqrt(a%2Fb)-sqrt(a)*(sqrt(b)%5E(-1))
Nope, it still requires that a and b are positive.

**Comment by jiggzson** [comment] 2018-03-06 13:44
Interesting. I'll take a look at this a little later. It seems this transform is a little more complicated than I thought.

**Comment by yosuke** [comment] 2018-03-06 23:49
@jiggzson @Happypig375 
For the bug part, I found this additional very strange behavior:
```
> nerdamer('1/sqrt(-1)').toString()
"i^(-1)"
```
```
> nerdamer('1/sqrt(-1)').evaluate({a:-1,b:-1}).text()
"-i+6.123233995736766e-17"
```
Both with same equation.

**Comment by yosuke** [comment] 2018-03-06 23:52
The second example can be actually simplified to:
```
> nerdamer('1/sqrt(-1)').evaluate().text()
"-i+6.123233995736766e-17"
```

**Comment by jiggzson** [comment] 2018-03-07 00:34
Ahhh. Captain Floating-Point-Errors strikes again. That isolates the problem and explains the strange results. I'll take care of both. @Happypig375 mentioned that the positive constraint exists for both transformation cases. I haven't had a chance to look into this but hopefully I can resolve that issue as well.
Thanks.

**Comment by jiggzson** [comment] 2018-03-07 02:52
@yosuke, ironically this one is related to #394. It appears that in order to fix this issue I need to first tackle that one. The problem is due to the fact that when evaluate is called the library switches to handling everything numerically and the precision problems start to pop up. Those are very very frustrating by the way. 

I've pushed a partial fix which changes the way `sqrt` handles fractions. Unfortunately I won't have a complete fix until #394 is fixed. If it's not too much of an inconvenience can you do a substitution without evaluating and then re-parse the whole thing? For example:

```javascript
var x = nerdamer('1/sqrt(b)', {b: -1});
console.log(x.toString());
//i^(-1)
console.log(nerdamer(x).evaluate().toString());
//-i
```
Hopefully I can get to this soon and provide a proper fix.

**Comment by yosuke** [comment] 2018-03-07 04:47
@jiggzson Thank you for the info. and no problem at all.

I have following very dirty workaround, which keep me safe from this issue (I currently don't need imaginary number).
```
    nerdamer.register({
        parent: 'Algebra',
        name: 'sqrt',
        visible: true,
        numargs: 1,
        build: function() {
            return function(a) {
                return _.symfunction('sqrt', [a]);
            };
        }
    });
```

**Comment by jiggzson** [comment] 2018-03-09 17:24
Awesome. Doesn't this solution get rid of numeric solutions altogether though?

**Comment by yosuke** [comment] 2018-03-10 04:49
Thank you for making clear. Yes, my evil workaround only prevent me from expanding sqrt which contains negative numbers, but does not solve the arithmetic  precision problem.

I found the following workaround may work for the precision issue for this specific problem:
```
> nerdamer.getCore().Settings.PRECISION=10
> nerdamer('1/sqrt(-1)').evaluate().text()
"-i"
```
Although, this is clearly not the absolute solution. Because the result is not proved to be stable for all the numbers.

I just had a fun time to investigate the changing point :)

```
> nerdamer.getCore().Settings.PRECISION=21
> nerdamer('1/sqrt(-1)').evaluate().text()
"-i"
> nerdamer.getCore().Settings.PRECISION=22
> nerdamer('1/sqrt(-1)').evaluate().text()
"-i+6.1232e-17"
```

**Comment by jiggzson** [comment] 2018-11-15 01:45
@yosuke, this should be fixed. Thanks for your patience.

**Comment by yosuke** [comment] 2018-11-15 05:09
Very nice!

Confirmed expected behavior on the following URL:
http://nerdamer.com/demo_dev.html

Thank you!

**Comment by jiggzson** [comment] 2018-11-15 12:00
@yosuke, no problem. Thank you for your help.

**Closed by jiggzson** 2018-11-15 12:00 UTC
Labels: bug
