### ISSUE TITLE
solve gives strange result

### ISSUE THREAD

**Issue by aliasal** [jiggzson/nerdamer#486] opened 2019-08-29 10:20 UTC
When I do:
var sol = nerdamer.solveEquations('sqrt(x)-2x+x^2','x');
console.log(sol.toString());
I get 
0, 1, 4503599627370497/4503599627370496

the correct results are
0, 1, (3-sqrt(5))/2

Why can it find 0 and 1 and then is not able to solve the remaining quadratic equation correctly?

**Comment by jiggzson** [comment] 2019-08-29 16:56
After first trying to solve the problem algebraically, nerdamer switches to numerical methods and as a result inherits all the limitations associated with them. The third point is more than likely a duplicate of the second one but with some floating point errors. I haven't tested it so I don't know for sure. Either way this a good case to solve for. I'll add this to the TODO list.

**Comment by jiggzson** [comment] 2019-08-30 17:30
@aliasal, this one is partially fixed. It's still gives `4503599627370497/4503599627370496` as a point so I'll probably need to implement some type of filter at some point. Moving this one to #322. If you run into any other solve issues, just add it under there.

**Closed by jiggzson** 2019-08-30 17:30 UTC
