### ISSUE TITLE
How to build nested functions in nerdamer?

### ISSUE THREAD

**Issue by MAGNETO903** [jiggzson/nerdamer#582] opened 2020-12-25 13:42 UTC
I have 2 simple functions:
`f1(x)=2*x`
`f2(x)=x^2`

I want to make a function `f3` that:
`f3(x) = f1(f2(x)) = f1(x^2) = 2x^2`

I type in nerdamer:
```
nerdamer.setFunction("a", ["x"], "2*x")
nerdamer.setFunction("b", ["x"], "x^2")

nerdamer("a(b(x))").text() // return 2*x instead of 2x^2

nerdamer.setFunction("c", ["x"], "a(b(x))"]
nerdamer("c(x)") // also 2*x instead of 2x^2
```

**Comment by jiggzson** [comment] 2020-12-28 15:26
@MAGNETO903, I suspect that the problem is related to confusion regarding the variable names. If you do, 
```javascript
nerdamer.setFunction("a", ["y"], "2*y");
nerdamer.setFunction("b", [], "x^2");

var ans = nerdamer("a(b(x))").text();
console.log(ans); // 2*x^2
```
it seems to give the expected result. 
Ironically I remember this not being the problem in past versions so I'm not sure when this broke. I'll take a look at this. Thanks.

**Comment by MAGNETO903** [comment] 2020-12-29 05:00
Ok!)

**Comment by jiggzson** [comment] 2021-02-16 18:29
@MAGNETO903, this issue should be fixed.

**Closed** 2021-02-19 01:07 UTC
Labels: bug
