### ISSUE TITLE
Infinity is treated as a normal symbol

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#148] opened 2017-08-14 03:49 UTC
nerdamer("Ei(0)+Ei(0)").evaluate().toString() returns -2*Infinity
What?? It should be -Infinity!

**Comment by jiggzson** [comment] 2017-08-14 12:41
I can have it return -Infinity when evaluating but other than that I don't see how this is a problem? Care to elaborate a bit on how it is?

**Comment by Happypig375** [comment] 2017-08-14 14:12
Oh wait... Sorry I misunderstood infinity arithmetic...
https://www.encyclopediaofmath.org/index.php/Infinity
> Infinity+Infinity is meaningless
So same would go for -Infinity-Infinity.
Meaningless operations should return undefined (I think)

So the problem is -Infinity-Infinity gets evaluated to -2*Infinity, which
>(-Infinity).a == +Infinity if x < 0

is Infinity. It should return undefined (This relates to #134).

**Comment by jiggzson** [comment] 2017-08-14 14:26
I just popped this one into Wolfram Alpha as well and (-1)*(-Infinity) gives infinity. I'm not particularly itching to add the undefined datatype since the effort required is enormous and the returns for this are minimal. I'd much rather throw an exception and leave it up the user to deal with it in a manner in which they feel to be appropriate. Feel free to give this one a go if it's an absolute must have. I'll help in any way I can.

**Comment by Happypig375** [comment] 2017-08-14 14:45
>not particularly itching to add the undefined datatype since the effort required is enormous

JavaScript has this...?

**Comment by jiggzson** [comment] 2017-08-14 14:52
This is true. But nerdamer takes JavaScript datatypes and tries to massage them a bit since JavaScript tends to be very permissive. This means that I would have to add some form of wrapper for undefined. Or return a blank string. Let me think about this one a bit more but off the top of my head it just seems like a lot of work for very little pay off. Maybe I can find a happy middle.

**Comment by jiggzson** [comment] 2017-08-14 21:23
Ahhh. I found a huge problem with this. Currently nerdamer assumes that -Infinity+Infinity = 0 which is big no no. I'll address this.

**Comment by Happypig375** [comment] 2017-09-23 14:29
Just hit `exp(1e6)-1` => `Infinity-1`. Reminded me of this issue. Any update on this?

**Comment by jiggzson** [comment] 2017-09-29 03:40
@Happypig375 The above mentioned issue seems to be related to #221. Closing this issue since it's a duplicate of #134

**Closed by jiggzson** 2017-09-29 03:40 UTC
