### ISSUE TITLE
solveFor returning an error

### ISSUE THREAD

**Issue by FilipeAC** [jiggzson/nerdamer#463] opened 2019-04-17 02:17 UTC
I'm not quite sure if this is a problem with solveFor or a deeper problem but whenever I try to execute the command 

**nerdamer("999999999*K + 7 = 0").solveFor("K")** 

the following error is returned.

E {name: "InvalidVariableNameError", message: " is not a valid variable name", stack: "InvalidVariableNameError:  is not a valid variable…nerdamer/Solve.js:854:16)↵    at <anonymous>:1:33"}

But if I try

**nerdamer("99999999*K + 7 = 0").solveFor("K")**

(there is one 9 less) Nerdamer returns the correct expression.

**Comment by jiggzson** [comment] 2019-04-20 18:30
@FilipeAC, this one has to do with rounding in `solve`. I'm rewriting the function to stop depending on JS `Number` which should take care of this. If you absolutely need a fix right away, let me know.

**Comment by FilipeAC** [comment] 2019-04-24 01:34
I'll try a workaround and wait for a future fix. I'll post here any progress if I find any.

**Comment by jiggzson** [comment] 2019-04-24 23:52
@FilipeAC, no workaround needed. I know exactly what the problem is. [This](https://github.com/jiggzson/nerdamer/blob/1fa6c5cbcd9b1f93f76ab68ba9d0573839801167/Algebra.js#L1710) line can be changed from
```javascript
real = round( zeror[i], decp );
```
to 
```javascript
real = round( zeror[i], decp+10 );
```
The error will go away but rounding error will be introduced to to the way floating point numbers are handled. It should go away permanently when I finish converting this function to use arbitrary precision.

**Comment by FilipeAC** [comment] 2019-04-26 00:21
Nice! It solved my problem. The error itself was the problem for me.

Thanks!

**Comment by jiggzson** [comment] 2019-04-29 01:33
@FilipeAC, great.

**Comment by jiggzson** [comment] 2019-08-19 15:09
Fixed.

**Closed by jiggzson** 2019-08-19 15:09 UTC
