### ISSUE TITLE
Abritrary large integers?

### ISSUE THREAD

**Issue by Happypig375** [jiggzson/nerdamer#196] opened 2017-08-28 06:57 UTC
Nerdamer home page:
>Nerdamer is modular so you only need to load the parts you need. Because of this and its small footprint, it can easily be embedded into your applications giving them **instant CAS capabilities**.

Computer Algebra System on Wikipedia:
>General-purpose computer algebra systems aim to be useful to a user working in any scientific field that requires manipulation of mathematical expressions. To be useful, a general-purpose computer algebra system **must** include various features such as:
>- an **arbitrary-precision arithmetic**, needed by the huge size of the integers that may occur.

Input: 2^2048

Algebrite: 32317006071311007300714876688669951960444102669715484032130345427524655138867890893197201411522913463688717960921898019494119559150490921095088152386448283120630877367300996091750197750389652106796057638384067568276792218642619756161838094338476170470581645852036305042887575891541065808607552399123930385521914333389668342420684974786564569494856176035326322058077805659331026192708460314150258592864177116725943603718461857357598351152301645904403697613233287231227125684710820209725157101726931323469678542580656697935045997268352998638215525166389437335543602135433229604645318478604952148193555853611059596230656

Nerdamer:
Error: Invalid integer: Infinity

The heck?

**Comment by jiggzson** [comment] 2017-08-28 11:37
>giving them instant CAS capabilities

Fixed. Removed from homepage.

**Comment by Happypig375** [comment] 2017-08-28 13:11
Soo... Please add this feature... This is really very  absolutely obviously definitely important.

**Comment by jiggzson** [comment] 2017-08-28 13:33
No problem.

**Comment by jiggzson** [comment] 2017-08-28 16:00
I'll lump this in with the parser update. This issue is due to the fact that nerdamer calls Math.pow somewhere. I must have forgotten to update it to use bigInteger.pow. It might also possibly be related to #164

**Comment by Happypig375** [comment] 2017-08-29 02:58
Ummm...
1e1000 => Error: Invalid integer: Infinity
1e200*1e200*1e200 => Infinity

Also...
1e200+1 => 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001 (No precision loss)

2^1023 => 89884656743115800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 (Precision lost)

**Comment by Happypig375** [comment] 2017-08-29 03:04
Also take a look at how demo displays large numbers:
1e308*1.234567890123456789012345667890123456789012345667890123456789012345667890123456789012345667890123456789 => 8916323500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000/72222221 (Displays as Infinity/72222221)

**Comment by Happypig375** [comment] 2017-08-29 03:08
171! => Infinity
1/1e308/10 => Error: Invalid integer: Infinity
Take a look at multiplication as well.

**Comment by jiggzson** [comment] 2017-11-29 21:46
This issue is technically fixed. The problem is that the demo still relies on the old toDecimal method which uses JS numbers instead of BigInteger numbers. Moving to demo related issue #247

**Closed by jiggzson** 2017-11-29 21:46 UTC
